server:
  port: 5000

spring:
  application:
    name: rentalbrain
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    #    RDS
    url: jdbc:mariadb://song-db.ch4g6m8q4u5j.ap-northeast-2.rds.amazonaws.com:3306/rentalbrain?useUnicode=true&characterEncoding=utf8&connectionCollation=utf8mb4_unicode_ci&useSsl=true&requireSsl=true&sslMode=TRUST
    username: admin
    password: adminadmin

    #    로컬 DB
<<<<<<< HEAD
    #    url: jdbc:mariadb://localhost:3306/rental_brain
    #    username: root
    #    password: mariadb
=======
#    url: jdbc:mariadb://localhost:3306/rental_brain
#    username: root
#    password: mariadb
>>>>>>> 55ead2388a4e3f7a67ccb8652166c58283281fa8

    hikari:
      pool-name: HikariPool-1
      minimum-idle: 10
      maximum-pool-size: 30
      idle-timeout: 600000
      max-lifetime: 1200000
      connection-timeout: 30000
      validation-timeout: 5000
      leak-detection-threshold: 20000

  jpa:
    generate-ddl: false
    show-sql: true
    database: mysql
    properties:
      hibernate:
        '[format_sql]': true
  data:
    redis:
      host: localhost
      port: 6379

opensearch:
  host: localhost
  port: 9200
token:
  access_secret: kqyT0btD7P3QA8RnLEtYdOY0vJdeKmo7fsL8bhfd+ICGmaOpYJQm5rUFkrJe9L/dULZUYuqE6DRkCuJt3hjDVQ==
  refresh_secret: JAJh5KPGaZ27mWSIm88QgafVMAlqpjeGEozhUsEDlmflx3tpCUHmtXOogzWSSA6UxFQdUiRMH8uagHRKGpf9Ag==
  access_expiration_time: 36000000
  refresh_expiration_time: 86400000

openai:
  api-key: ${OPENAI_API_KEY}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html